title: DaMiao FE-training
description: A site to commit classwork.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

classwork:
  zip_url: tree/main/docs/last/last.zip
  raw_url: tree/main/docs/raw/