title: DaMiao FE-training
description: A site to commit classwork.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

classwork:
  zip_url: https://nyanyani.github.io/docs/last/last.zip
  raw_url: https://nyanyani.github.io/docs/raw/
